language: node_js
node_js:
  - "6"
before_script:
  - cd functions/sum
  - npm install
before_install:
  - sudo pip install --upgrade pip
install:
  - sudo pip install awscli
  - "./travis-install-apex.sh"
after_success:
  - cd ../../
  - ./apex deploy
