language: node_js
node_js:
  - "6"
before_script:
  - cd functions/sum
  - npm install
before_install:
  - pip install --upgrade --user pip
  - pip install awscli
  - cd ../../
  - "./travis-install-apex.sh"
deploy:
  - provider: script
    skip_cleanup: true
    script: ./apex deploy
