language: node_js
node_js:
  - "6"
env:
  - TEST_DIR=functions/sum
  - TEST_DIR=functions/show
script:
  - cd $TEST_DIR && npm install && npm test
before_install:
  - sudo pip install --upgrade pip
install:
  - sudo pip install awscli
  - "./travis-install-apex.sh"
after_success:
  - cd ../../
  - "./travis-apex-deploy.sh"
