language: node_js
node_js:
  - "6"
script:
  - cd functions/sum && npm install && npm test
  - cd functions/show && npm install && npm test
before_install:
  - sudo pip install --upgrade pip
install:
  - sudo pip install awscli
  - "./travis-install-apex.sh"
after_success:
  - cd ../../
  - "./travis-apex-deploy.sh"
